apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: staging
  labels:
    app: fastapi-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-service
  template:
    metadata:
      labels:
        app: fastapi-service
    spec:
      containers:
        - name: fastapi-container
          image: ghcr.io/aiswarya1987/TemenosProject:$IMAGE_TAG 
          ports:
            - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
