name: FASTAPI CI/CD

on:
  push:
    branches-ignore:
      - main
      - npe
    
  pull_request:
    branches: 
      - main
      
env:
   DOCKER_IMAGE: ghcr.io/${{ github.repository }}
   K8S_NAMESPACE: staging
   PYTHON_VERSION: "3.11"
   APP_PORT: 8080
   IMAGE_NAME: ${{ github.repository_owner }}/fastapi
   IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # needed to oush to /ghcr

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
  
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ env.PYTHON_VERSION }}
  
      - name: Install dependencies
        run: pip install -r requirements.txt
  
      - name: Run Test Suite
        run: pytest
        continue-on-error: false

      - name: Login in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker (SHA tag)
        id: meta
        uses: docker/metadata-action@v5
        with:
           images: ${{ env.DOCKER_IMAGE }}
           tags: |
            type=sha,prefix= 

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        id: docker_build
        with:
          context: .
          push: true
          #tags: ${{ steps.meta.outputs.tags }}
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{env.IMAGE_TAG }}
         # outputs: type=local, dest=./image-output

      - name: Set image Variable
        run: echo "IMAGE=ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'
      - name: Start Minikube
        run: minikube start --driver=docker
        
      - name: configure kubeconfig
        run: | 
           echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
           
       # run: |
       #   mkdir -p $HOME/.kube
       #   echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
       # env:
       #   KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        
      - name: Deploy to K8s
        run: |
          envsubst < k8s/deployment.yaml > k8s/deployment.final.yaml
          
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/deployment.final.yaml
          #echo "kubectl apply -f k8s/deployment.final.yaml" >> $GITHUB_ENV
          kubectl apply -f k8s/service.yaml
          env:
            IMAGE_TAG: ${{ env.IMAGE_TAG }}
           
      #- name: Wait for Deployment
        #run: kubectl rollout status deployment/fastapi-deployment -n 
        
      - name: Get Service URL
        run: minikube service fastapi-service -n Staging --url
        
      # to deploy only the image tag
  
