name: FASTAPI CI/CD

on:
  push:
    branches-ignore:
      - main
      - npe
    
  pull_request:
    branches: 
      - main
      
env:
   DOCKER_IMAGE: ghcr.io/${{ github.repositry }}
   K8S_NAMESPACE: Staging
   PYTHON_VERSION: "3.11"
   APP_PORT: 8080
   IMAGE_NAME: ${{ github.repository_owner }}/fastapi
   IMAGE_TAG: ${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
  
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ env.PYTHON_VERSION }}
  
      - name: Install dependencies
        run: pip install -r requirements.txt
  
      - name: Run Test Suite
        run: pytest
        continue-on-error: false

      - name: Login in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    #  - name: Extract metadata for Docker (SHA tag)
    #   id: meta
    #    uses: docker/metadata-action@v5
    #    with:
    #      images: ${{ env.DOCKER_IMAGE }}
    #      tags: |
    #       type=sha,prefix= #>

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{env.IMAGE_TAG }}
          outputs: type=local, dest=./image-output

      - name: Set image Variable
        run: echo "IMAGE=ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
